# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: linux

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: InstallFortifySCA@7
  inputs:
    InstallerPath: '/agent/fortify/Fortify_SCA_and_Apps_21.2.0_linux_x64.run'
    VS2015: false
    LicenseFile: '/agent/fortify/fortify.license'
    RunFortifyRulepackUpdate: false

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      /agent/_work/1/a/sca_artifacts/test.sh
      echo Hello world
    failOnStderr: true